module.exports = {
  content: ['./src/**/*.{html,ts}'],
  theme: {
    colors: {
      primary: 'var(--primary)',
      secondary: 'var(--secondary)',
      'bg-primary': 'var(--bg-primary)',
      'bg-secondary': 'var(--bg-secondary)',
      'bg-light': 'var(--bg-light)',
      'bg-light-gray': 'var(--bg-light-gray)',
      'bg-dark-blue': 'var(--bg-dark-blue)',
      'bg-active': 'var(--bg-active)',
      'bg-success': 'var(--bg-success)',
      'bg-danger': 'var(--bg-danger)',
      'bg-warning': 'var(--bg-warning)',
      'bg-info': 'var(--bg-info)',
      'bd-gray': 'var(--bd-gray)',
      'bd-light-gray': 'var(--bd-light-gray)',
      'bd-light': 'var(--bd-light)',
      'bd-primary': 'var(--bd-primary)',
      'text-base': 'var(--text-base)',
      'text-secondary': 'var(--text-secondary)',
      'text-gray': 'var(--text-gray)',
      'text-white': 'var(--text-white)',
      'text-success': 'var(--text-success)',
      'text-danger': 'var(--text-danger)',
      'text-warning': 'var(--text-warning)',
      'text-active': 'var(--text-active)',
      'text-dark-blue': 'var(--text-dark-blue)',
    },
    extend: {
      padding: {
        1.25: '5px',
      },
      boxShadow: {
        sm: 'var(--box-shadow)',
      },
      fontSize: {
        xxl: 'var(--font-size-xxl)',
        xl: 'var(--font-size-xl)',
        l: 'var(--font-size-l)',
        m: 'var(--font-size-m)',
        s: 'var(--font-size-s)',
      },
      borderRadius: {
        s: 'var(--border-radius-s)',
        m: 'var(--border-radius-m)',
        l: 'var(--border-radius-l)',
        xl: 'var(--border-radius-xl)',
      },
    },
  },
  plugins: [],
};
